### ISSUE TITLE
cmd(when)

### ISSUE THREAD

**Issue by ujeropoc** [wonkodv/hanstool#2]
cmd(when=not ('win' in Filter.os or 'ht3.cli' in Filter.frontend))

ht3.lib loads ht3.filter very early

ht3.Filter has

os: ['unix','linux'] or ['windows','windows vista']
arch: ['arm','arm7-m'] or ['x86','32bit']
frontend = ['ht3.cli',ht3.hotkey']

Frontends set Env.Filter.front to module.qualname early

Scripts can raise a NotImplemented Exception if they want to filter out the whole  script.

**Comment by wonkodv** [comment]
```
if ht3.lib.Check.os.win or ht3.lib.Check.frontend('ht3.cli')
    @cmd
    def ...
```
