### ISSUE TITLE
Hotkey Frontend

### ISSUE THREAD

**Issue by ujeropoc** [wonkodv/hanstool#3]
All Frontends implement the following set of module-level methods
- start() do things
- stop() stop doing things
  start and stop are not (!) executed from the same thread.
  if start returns, stop is not called.
  when a frontend module is loaded, ht3.lib.Env is fully initialized, scripts might have already been executed. Install commands and Env objects on module scope.

Frontends are loaded by `ht3.__main__` depending on `if` arguments, for example to load all frontends do `python -m ht3 -s scripts -f ht3.hotkey -f ht3.gui -f ht3.cli`

Commands are executed from the thread of the frontend without any syncronization by default.
if they have the attribute async, they are executed in their own thread, if they have the attribute sync, they are queued for execution by one thread. Defaults for sync and async are false, but this may change.

**Comment by ujeropoc** [comment]
The Env contains a method `_report_exception` which can be implemented by cli or gui frontend and is called by run_command on any kind of exception. it should reraise Shutdown, cli should catch KeyboardInterrupt and the rest should be caught and displayed.

**Comment by wonkodv** [comment]
there won't be a `sync` attribute for now.
